### ISSUE TITLE
Fail error

### ISSUE THREAD

**Issue by BrunoHeinich** [amandaghassaei/Fusion360-Design-History-Animation#3]
Failed:
Traceback (most recent call last):
  File "C:/Users/bruno/OneDrive/Documents/Fusion 360/Fusion360-Scripts-main/Design-History-Animation/Design-History-Animation/Design-History-Animation.py", line 48, in notify
    timelapse.collectFrames()
  File "C:/Users/bruno/OneDrive/Documents/Fusion 360/Fusion360-Scripts-main/Design-History-Animation/Design-History-Animation/Design-History-Animation.py", line 302, in collectFrames
    if self.isNumericExtent(entity.extentOne):
  File "C:/Users/bruno/AppData/Local/Autodesk/webdeploy/production/eba7fbfbb17ff9a9d7c25530f6f766b5ffb15678/Api/Python/packages\adsk\fusion.py", line 50882, in _get_extentOne
    return _fusion.ExtrudeFeature__get_extentOne(self)
RuntimeError: 2 : InternalValidationError : extrude

Any help?

**Comment by amandaghassaei** [comment]
Can you tell which extrude this is from in your design?  How is it set up?  I guess some extrude commands do not have an extentOne property.  If you figure it out, feel free to submit a PR.  This code def does not cover all the possibilities as it currently stands.

**Comment by BrunoHeinich** [comment]
Thx for reaching out but I figured I it out differently.
